# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Matteo/Desktop/Esercitazione3/no_opt/no_opt.cache/wt [current_project]
set_property parent.project_path C:/Users/Matteo/Desktop/Esercitazione3/no_opt/no_opt.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/Matteo/Desktop/Esercitazione3/no_opt/no_opt.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/specialistica/SECONDO_ANNO/PRIMO_SEMESTRE/LOW_POWER/file/prof/FA.vhd
  D:/specialistica/SECONDO_ANNO/PRIMO_SEMESTRE/LOW_POWER/file/prof/MUX32.vhd
  D:/specialistica/SECONDO_ANNO/PRIMO_SEMESTRE/LOW_POWER/file/prof/RCA32.vhd
  D:/specialistica/SECONDO_ANNO/PRIMO_SEMESTRE/LOW_POWER/file/prof/RCA8.vhd
  D:/specialistica/SECONDO_ANNO/PRIMO_SEMESTRE/LOW_POWER/file/prof/parity_check.vhd
  D:/specialistica/SECONDO_ANNO/PRIMO_SEMESTRE/LOW_POWER/file/prof/TOP_1_RCA.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Matteo/Desktop/Esercitazione3/no_opt/no_opt.srcs/constrs_1/new/clk_2.xdc
set_property used_in_implementation false [get_files C:/Users/Matteo/Desktop/Esercitazione3/no_opt/no_opt.srcs/constrs_1/new/clk_2.xdc]


synth_design -top TOP_1_RCA -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_1_RCA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_1_RCA_utilization_synth.rpt -pb TOP_1_RCA_utilization_synth.pb"
